
package jobme.pk;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class NewJFrame extends javax.swing.JFrame implements abcd {

    /**
     * Creates new form NewJFrame
     */
     public void sizeee(){
          Toolkit tk = getToolkit();
        Dimension size = tk.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    public NewJFrame() {
        initComponents();
        sizeee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASTER TIMETABLE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("CSE-A");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("CSE-B");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("ECE-A");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("ECE-B");

        jButton1.setText("1st YEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2nd YEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3rd YEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4th YEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "8:50-9:40", "9:50-10:40", "11:00-11:50", "12:00-12:50", "2:00-2:50", "3:00-3:50"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "8:50-9:40", "9:50-10:40", "11:00-11:50", "12:00-12:50", "2:00-2:50", "3:00-3:50"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "8:50-9:40", "9:50-10:40", "11:00-11:50", "12:00-12:50", "2:00-2:50", "3:00-3:50"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "8:50-9:40", "9:50-10:40", "11:00-11:50", "12:00-12:50", "2:00-2:50", "3:00-3:50"
            }
        ));
        jScrollPane7.setViewportView(jTable4);

        jButton5.setText("RESET");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton1)
                                .addGap(104, 104, 104)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(73, 73, 73)
                                .addComponent(jButton4)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel3)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel5)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable1";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
            }
             Statement ste = con.createStatement();
             String sq = "Select * from timetable1";
            ResultSet rse = ste.executeQuery(sq);
            while(rse.next()){
               String Day = rse.getString("day");
               String Period_1 = rse.getString("period5");
               String Period_2 = rse.getString("period2");
               String Period_3 = rse.getString("period6");
               String Period_4 = rse.getString("period4");
               String Period_5 = rse.getString("period1");
               String Period_6 = rse.getString("period3");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable2.getModel();  
               
               x.addRow(tbData);
                 
           }
            Statement str = con.createStatement();
            String sqle = "Select * from timetable1";
            ResultSet rsr = str.executeQuery(sqle);
            while(rsr.next()){
               String Day = rsr.getString("day");
               String Period_1 = rsr.getString("period2");
               String Period_2 = rsr.getString("period1");
               String Period_3 = rsr.getString("period4");
               String Period_4 = rsr.getString("period3");
               String Period_5 = rsr.getString("period6");
               String Period_6 = rsr.getString("period5");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable3.getModel();  
               
               x.addRow(tbData);
                 
            }
            Statement stt = con.createStatement();  
            String sqli = "Select * from timetable1";
            ResultSet rst = stt.executeQuery(sqli);
            while(rst.next()){
               String Day = rst.getString("day");
               String Period_1 = rst.getString("period5");
               String Period_2 = rst.getString("period3");
               String Period_3 = rst.getString("period6");
               String Period_4 = rst.getString("period4");
               String Period_5 = rst.getString("period1");
               String Period_6 = rst.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable4.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close();
            } 
          catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
            }
             Statement ste = con.createStatement();
             String sq = "Select * from timetable";
            ResultSet rse = ste.executeQuery(sq);
            while(rse.next()){
               String Day = rse.getString("day");
               String Period_1 = rse.getString("period5");
               String Period_2 = rse.getString("period2");
               String Period_3 = rse.getString("period6");
               String Period_4 = rse.getString("period4");
               String Period_5 = rse.getString("period1");
               String Period_6 = rse.getString("period3");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable2.getModel();  
               
               x.addRow(tbData);
                 
           }
            Statement str = con.createStatement();
            String sqle = "Select * from timetable4";
            ResultSet rsr = str.executeQuery(sqle);
            while(rsr.next()){
               String Day = rsr.getString("day");
               String Period_1 = rsr.getString("period1");
               String Period_2 = rsr.getString("period2");
               String Period_3 = rsr.getString("period3");
               String Period_4 = rsr.getString("period4");
               String Period_5 = rsr.getString("period5");
               String Period_6 = rsr.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable3.getModel();  
               
               x.addRow(tbData);
                 
            }
            Statement stt = con.createStatement();  
            String sqli = "Select * from timetable4";
            ResultSet rst = stt.executeQuery(sqli);
            while(rst.next()){
               String Day = rst.getString("day");
               String Period_1 = rst.getString("period5");
               String Period_2 = rst.getString("period3");
               String Period_3 = rst.getString("period6");
               String Period_4 = rst.getString("period4");
               String Period_5 = rst.getString("period1");
               String Period_6 = rst.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable4.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close();
        }
          catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable2";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String Day = rs.getString("day");
               String Period_1 = rs.getString("period5");
               String Period_2 = rs.getString("period3");
               String Period_3 = rs.getString("period6");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period1");
               String Period_6 = rs.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
            }
             Statement ste = con.createStatement();
             String sq = "Select * from timetable2";
            ResultSet rse = ste.executeQuery(sq);
            while(rse.next()){
               String Day = rse.getString("day");
               String Period_1 = rse.getString("period1");
               String Period_2 = rse.getString("period2");
               String Period_3 = rse.getString("period3");
               String Period_4 = rse.getString("period4");
               String Period_5 = rse.getString("period5");
               String Period_6 = rse.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable2.getModel();  
               
               x.addRow(tbData);
                 
           }
            Statement str = con.createStatement();
            String sqle = "Select * from timetable5";
            ResultSet rsr = str.executeQuery(sqle);
            while(rsr.next()){
               String Day = rsr.getString("day");
               String Period_1 = rsr.getString("period1");
               String Period_2 = rsr.getString("period2");
               String Period_3 = rsr.getString("period3");
               String Period_4 = rsr.getString("period4");
               String Period_5 = rsr.getString("period5");
               String Period_6 = rsr.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable3.getModel();  
               
               x.addRow(tbData);
                 
            }
            Statement stt = con.createStatement();  
            String sqli = "Select * from timetable5";
            ResultSet rst = stt.executeQuery(sqli);
            while(rst.next()){
               String Day = rst.getString("day");
               String Period_1 = rst.getString("period5");
               String Period_2 = rst.getString("period3");
               String Period_3 = rst.getString("period6");
               String Period_4 = rst.getString("period4");
               String Period_5 = rst.getString("period1");
               String Period_6 = rst.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable4.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new NewJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ttms","root","");
            Statement st = con.createStatement();
            String sql = "Select * from timetable3";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String Day = rs.getString("day");
               String Period_1 = rs.getString("period1");
               String Period_2 = rs.getString("period2");
               String Period_3 = rs.getString("period3");
               String Period_4 = rs.getString("period4");
               String Period_5 = rs.getString("period5");
               String Period_6 = rs.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable1.getModel();  
               
               x.addRow(tbData);
            }
             Statement ste = con.createStatement();
             String sq = "Select * from timetable3";
            ResultSet rse = ste.executeQuery(sq);
            while(rse.next()){
               String Day = rse.getString("day");
               String Period_1 = rse.getString("period5");
               String Period_2 = rse.getString("period2");
               String Period_3 = rse.getString("period6");
               String Period_4 = rse.getString("period4");
               String Period_5 = rse.getString("period1");
               String Period_6 = rse.getString("period3");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable2.getModel();  
               
               x.addRow(tbData);
                 
           }
            Statement str = con.createStatement();
            String sqle = "Select * from timetable6";
            ResultSet rsr = str.executeQuery(sqle);
            while(rsr.next()){
               String Day = rsr.getString("day");
               String Period_1 = rsr.getString("period1");
               String Period_2 = rsr.getString("period2");
               String Period_3 = rsr.getString("period3");
               String Period_4 = rsr.getString("period4");
               String Period_5 = rsr.getString("period5");
               String Period_6 = rsr.getString("period6");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable3.getModel();  
               
               x.addRow(tbData);
                 
            }
            Statement stt = con.createStatement();  
            String sqli = "Select * from timetable6";
            ResultSet rst = stt.executeQuery(sqli);
            while(rst.next()){
               String Day = rst.getString("day");
               String Period_1 = rst.getString("period5");
               String Period_2 = rst.getString("period3");
               String Period_3 = rst.getString("period6");
               String Period_4 = rst.getString("period4");
               String Period_5 = rst.getString("period1");
               String Period_6 = rst.getString("period2");
               
               String tbData[] ={Day,Period_1, Period_2,Period_3,Period_4,Period_5,Period_6};
               DefaultTableModel x = (DefaultTableModel)jTable4.getModel();  
               
               x.addRow(tbData);
                 
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       new Admin4().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void sizeeee() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
